name: Run PushpaFrames Bot

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 60 minutes
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python and install dependencies
    - name: Set up Python and install dependencies
      run: |
        python3 -m venv venv  # Create virtual environment
        source venv/bin/activate  # Activate virtual environment
        pip install tweepy  # Install tweepy

    # Step 3: Run the bot script
    - name: Run the bot script
      run: |
        source venv/bin/activate  # Activate virtual environment
        python main.py  # Run the main script
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "Github Actions"
        git add current_frame.txt
        git commit -m "Update current_frame.txt"
        git push --force https://x-access-token:${{ secrets.GH_PAT }}@github.com/Teluguswagger/PushpaFrames.git HEAD:master 
      env:
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        GH_PAT: ${{ secrets.GH_PAT }}  # Use the PAT stored in GitHub Secrets
