name: Run bot 

on:
  schedule:
    - cron: '*/5 * * * *'
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install tweepy

    - name: Run the bot
      run: |
        python main.py

    - name: Commit and push current_frame.txt
      run: |
        git config --global user.email "Tharunteja2u@gmail.com"
        git config --global user.name "Teluguswagger"
        git add current_frame.txt
        git commit -m "Update current_frame.txt"
        git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/Teluguswagger/PushpaFrames.git master
      
    env:
        TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
        TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        GH_PAT: ${{ secrets.GH_PAT }}
